In [17]:
from autorec import *
import sys, importlib
importlib.reload(sys.modules['movielens_recommender'])
importlib.reload(sys.modules['autorec'])
from autorec import *

In [6]:
autorec

In [29]:
item = np.array([[0.9*3, 0, 0, 0]], dtype='float32')

In [30]:
autorec.model.predict(item)

array([[0.24592996, 0.08943301, 0.7530067 , 0.46349978]], dtype=float32)

In [16]:
for i in range(1000):
    autorec.training_step(batch=ratings, batch_mask=ratings_mask)

In [32]:
np.array([[1, 2, 3, 4]], dtype='float32') * np.array([[1, 0, 1, 0]], dtype='float32')

array([[1., 0., 3., 0.]], dtype=float32)

In [33]:
ratings = np.array(
    [[0.1, 0.9, 1.0],
     [0.3, 0.8, 0.8],
     [0.8, 0.1, 0.2],
     [0.7, 0.1, 0.1]], dtype='float32').transpose()

In [35]:
ratings[[0,2], :]

array([[0.1, 0.3, 0.8, 0.7],
       [1. , 0.8, 0.2, 0.1]], dtype=float32)

In [36]:
ratings

array([[0.1, 0.3, 0.8, 0.7],
       [0.9, 0.8, 0.1, 0.1],
       [1. , 0.8, 0.2, 0.1]], dtype=float32)

In [159]:
autorec = train_movielens(k=100, epochs=2000, alpha=0.05, optimizer=keras.optimizers.Adam(lr=1e-4))

Epoch 0 of 2000. Loss per movie: 15.369809188117028, test rmse: 3.61223, train rmse: 3.60319
Epoch 1 of 2000. Loss per movie: 14.443714513506531, test rmse: 3.48392, train rmse: 3.47304
Epoch 2 of 2000. Loss per movie: 13.335557472124679, test rmse: 3.31148, train rmse: 3.29994
Epoch 3 of 2000. Loss per movie: 11.971447904384943, test rmse: 3.11214, train rmse: 3.10114
Epoch 4 of 2000. Loss per movie: 10.539001341807289, test rmse: 2.91092, train rmse: 2.89954
Epoch 5 of 2000. Loss per movie: 9.202884491502035, test rmse: 2.71917, train rmse: 2.70734
Epoch 6 of 2000. Loss per movie: 8.020915666176505, test rmse: 2.53994, train rmse: 2.52812
Epoch 7 of 2000. Loss per movie: 6.996769110739727, test rmse: 2.37513, train rmse: 2.36331
Epoch 8 of 2000. Loss per movie: 6.11734425241967, test rmse: 2.22374, train rmse: 2.21192
Epoch 9 of 2000. Loss per movie: 5.362564938530485, test rmse: 2.08555, train rmse: 2.07359
Epoch 10 of 2000. Loss per movie: 4.717223744330027, test rmse: 1.95990, tra

Epoch 88 of 2000. Loss per movie: 0.984404605790069, test rmse: 0.95636, train rmse: 0.93157
Epoch 89 of 2000. Loss per movie: 0.9829952509167929, test rmse: 0.95588, train rmse: 0.93091
Epoch 90 of 2000. Loss per movie: 0.9816186087168355, test rmse: 0.95542, train rmse: 0.93026
Epoch 91 of 2000. Loss per movie: 0.9802725431326595, test rmse: 0.95497, train rmse: 0.92962
Epoch 92 of 2000. Loss per movie: 0.9789546465902068, test rmse: 0.95453, train rmse: 0.92900
Epoch 93 of 2000. Loss per movie: 0.9776622754356665, test rmse: 0.95410, train rmse: 0.92839
Epoch 94 of 2000. Loss per movie: 0.9763926380312825, test rmse: 0.95368, train rmse: 0.92779
Epoch 95 of 2000. Loss per movie: 0.9751430854786024, test rmse: 0.95327, train rmse: 0.92719
Epoch 96 of 2000. Loss per movie: 0.9739110303974038, test rmse: 0.95287, train rmse: 0.92661
Epoch 97 of 2000. Loss per movie: 0.9726946849318379, test rmse: 0.95248, train rmse: 0.92603
Epoch 98 of 2000. Loss per movie: 0.9714946747534907, test rm

Epoch 175 of 2000. Loss per movie: 0.8929533744396976, test rmse: 0.92659, train rmse: 0.88702
Epoch 176 of 2000. Loss per movie: 0.8920786444554005, test rmse: 0.92632, train rmse: 0.88658
Epoch 177 of 2000. Loss per movie: 0.8912098502715902, test rmse: 0.92605, train rmse: 0.88615
Epoch 178 of 2000. Loss per movie: 0.8903470340580208, test rmse: 0.92578, train rmse: 0.88572
Epoch 179 of 2000. Loss per movie: 0.889490255206717, test rmse: 0.92552, train rmse: 0.88529
Epoch 180 of 2000. Loss per movie: 0.8886395587223747, test rmse: 0.92526, train rmse: 0.88487
Epoch 181 of 2000. Loss per movie: 0.887794920224497, test rmse: 0.92500, train rmse: 0.88445
Epoch 182 of 2000. Loss per movie: 0.8869564105866213, test rmse: 0.92475, train rmse: 0.88403
Epoch 183 of 2000. Loss per movie: 0.8861240954376429, test rmse: 0.92450, train rmse: 0.88362
Epoch 184 of 2000. Loss per movie: 0.8852979371437136, test rmse: 0.92425, train rmse: 0.88321
Epoch 185 of 2000. Loss per movie: 0.884478049031619

Epoch 262 of 2000. Loss per movie: 0.8379421752925151, test rmse: 0.91070, train rmse: 0.85935
Epoch 263 of 2000. Loss per movie: 0.8375032221661454, test rmse: 0.91058, train rmse: 0.85913
Epoch 264 of 2000. Loss per movie: 0.83706733354065, test rmse: 0.91047, train rmse: 0.85890
Epoch 265 of 2000. Loss per movie: 0.8366345187004625, test rmse: 0.91035, train rmse: 0.85868
Epoch 266 of 2000. Loss per movie: 0.8362047232147063, test rmse: 0.91023, train rmse: 0.85846
Epoch 267 of 2000. Loss per movie: 0.8357779395707864, test rmse: 0.91012, train rmse: 0.85824
Epoch 268 of 2000. Loss per movie: 0.8353540845631703, test rmse: 0.91000, train rmse: 0.85803
Epoch 269 of 2000. Loss per movie: 0.8349331531598366, test rmse: 0.90989, train rmse: 0.85781
Epoch 270 of 2000. Loss per movie: 0.8345150910716561, test rmse: 0.90978, train rmse: 0.85760
Epoch 271 of 2000. Loss per movie: 0.8340998460648318, test rmse: 0.90967, train rmse: 0.85739
Epoch 272 of 2000. Loss per movie: 0.833687398436520

Epoch 349 of 2000. Loss per movie: 0.808099657049077, test rmse: 0.90321, train rmse: 0.84399
Epoch 350 of 2000. Loss per movie: 0.807827414570467, test rmse: 0.90315, train rmse: 0.84385
Epoch 351 of 2000. Loss per movie: 0.8075563781468394, test rmse: 0.90309, train rmse: 0.84370
Epoch 352 of 2000. Loss per movie: 0.8072865677645317, test rmse: 0.90303, train rmse: 0.84356
Epoch 353 of 2000. Loss per movie: 0.807017983848785, test rmse: 0.90297, train rmse: 0.84342
Epoch 354 of 2000. Loss per movie: 0.8067505981919315, test rmse: 0.90290, train rmse: 0.84329
Epoch 355 of 2000. Loss per movie: 0.806484397044505, test rmse: 0.90284, train rmse: 0.84315
Epoch 356 of 2000. Loss per movie: 0.8062193648143274, test rmse: 0.90278, train rmse: 0.84301
Epoch 357 of 2000. Loss per movie: 0.8059555576332401, test rmse: 0.90273, train rmse: 0.84287
Epoch 358 of 2000. Loss per movie: 0.8056928694035579, test rmse: 0.90267, train rmse: 0.84274
Epoch 359 of 2000. Loss per movie: 0.8054313500911245,

Epoch 436 of 2000. Loss per movie: 0.7882614853691119, test rmse: 0.89920, train rmse: 0.83362
Epoch 437 of 2000. Loss per movie: 0.7880719197774472, test rmse: 0.89917, train rmse: 0.83352
Epoch 438 of 2000. Loss per movie: 0.7878830785842061, test rmse: 0.89913, train rmse: 0.83342
Epoch 439 of 2000. Loss per movie: 0.7876949975805249, test rmse: 0.89910, train rmse: 0.83332
Epoch 440 of 2000. Loss per movie: 0.7875075983093979, test rmse: 0.89907, train rmse: 0.83322
Epoch 441 of 2000. Loss per movie: 0.787320950156018, test rmse: 0.89904, train rmse: 0.83312
Epoch 442 of 2000. Loss per movie: 0.787135012864216, test rmse: 0.89901, train rmse: 0.83302
Epoch 443 of 2000. Loss per movie: 0.786949776653444, test rmse: 0.89898, train rmse: 0.83293
Epoch 444 of 2000. Loss per movie: 0.7867652588168449, test rmse: 0.89895, train rmse: 0.83283
Epoch 445 of 2000. Loss per movie: 0.7865814488651353, test rmse: 0.89892, train rmse: 0.83273
Epoch 446 of 2000. Loss per movie: 0.7863983519720833

Epoch 523 of 2000. Loss per movie: 0.7742092406707202, test rmse: 0.89714, train rmse: 0.82619
Epoch 524 of 2000. Loss per movie: 0.7740727171886549, test rmse: 0.89712, train rmse: 0.82612
Epoch 525 of 2000. Loss per movie: 0.7739366701185065, test rmse: 0.89710, train rmse: 0.82604
Epoch 526 of 2000. Loss per movie: 0.773801109595191, test rmse: 0.89709, train rmse: 0.82597
Epoch 527 of 2000. Loss per movie: 0.7736660377449145, test rmse: 0.89707, train rmse: 0.82590
Epoch 528 of 2000. Loss per movie: 0.773531436778419, test rmse: 0.89705, train rmse: 0.82583
Epoch 529 of 2000. Loss per movie: 0.7733972979782594, test rmse: 0.89704, train rmse: 0.82576
Epoch 530 of 2000. Loss per movie: 0.7732636382832113, test rmse: 0.89702, train rmse: 0.82569
Epoch 531 of 2000. Loss per movie: 0.7731304759077736, test rmse: 0.89700, train rmse: 0.82562
Epoch 532 of 2000. Loss per movie: 0.7729977359386176, test rmse: 0.89699, train rmse: 0.82555
Epoch 533 of 2000. Loss per movie: 0.772865504487090

Epoch 610 of 2000. Loss per movie: 0.7639344428155425, test rmse: 0.89600, train rmse: 0.82071
Epoch 611 of 2000. Loss per movie: 0.7638329870635633, test rmse: 0.89599, train rmse: 0.82066
Epoch 612 of 2000. Loss per movie: 0.7637318795841458, test rmse: 0.89598, train rmse: 0.82061
Epoch 613 of 2000. Loss per movie: 0.763631115628763, test rmse: 0.89597, train rmse: 0.82055
Epoch 614 of 2000. Loss per movie: 0.763530660115014, test rmse: 0.89596, train rmse: 0.82050
Epoch 615 of 2000. Loss per movie: 0.763430557905848, test rmse: 0.89595, train rmse: 0.82045
Epoch 616 of 2000. Loss per movie: 0.7633307790217587, test rmse: 0.89594, train rmse: 0.82039
Epoch 617 of 2000. Loss per movie: 0.7632313472762544, test rmse: 0.89593, train rmse: 0.82034
Epoch 618 of 2000. Loss per movie: 0.7631322577081877, test rmse: 0.89592, train rmse: 0.82029
Epoch 619 of 2000. Loss per movie: 0.7630334666594597, test rmse: 0.89591, train rmse: 0.82023
Epoch 620 of 2000. Loss per movie: 0.7629350423104131

Epoch 697 of 2000. Loss per movie: 0.7561725733112921, test rmse: 0.89536, train rmse: 0.81655
Epoch 698 of 2000. Loss per movie: 0.7560936756848439, test rmse: 0.89535, train rmse: 0.81651
Epoch 699 of 2000. Loss per movie: 0.7560150039323587, test rmse: 0.89535, train rmse: 0.81647
Epoch 700 of 2000. Loss per movie: 0.7559365581955836, test rmse: 0.89534, train rmse: 0.81643
Epoch 701 of 2000. Loss per movie: 0.7558583262133967, test rmse: 0.89534, train rmse: 0.81639
Epoch 702 of 2000. Loss per movie: 0.7557802915431373, test rmse: 0.89533, train rmse: 0.81634
Epoch 703 of 2000. Loss per movie: 0.7557025025205578, test rmse: 0.89532, train rmse: 0.81630
Epoch 704 of 2000. Loss per movie: 0.755624910172044, test rmse: 0.89532, train rmse: 0.81626
Epoch 705 of 2000. Loss per movie: 0.7555475658809104, test rmse: 0.89531, train rmse: 0.81622
Epoch 706 of 2000. Loss per movie: 0.7554703989862404, test rmse: 0.89531, train rmse: 0.81618
Epoch 707 of 2000. Loss per movie: 0.75539345980824

Epoch 784 of 2000. Loss per movie: 0.7500223481981139, test rmse: 0.89497, train rmse: 0.81324
Epoch 785 of 2000. Loss per movie: 0.7499588844183651, test rmse: 0.89497, train rmse: 0.81321
Epoch 786 of 2000. Loss per movie: 0.7498955470770066, test rmse: 0.89496, train rmse: 0.81317
Epoch 787 of 2000. Loss per movie: 0.7498323637438444, test rmse: 0.89496, train rmse: 0.81314
Epoch 788 of 2000. Loss per movie: 0.7497693262684217, test rmse: 0.89496, train rmse: 0.81310
Epoch 789 of 2000. Loss per movie: 0.7497064248701906, test rmse: 0.89495, train rmse: 0.81307
Epoch 790 of 2000. Loss per movie: 0.749643665006413, test rmse: 0.89495, train rmse: 0.81304
Epoch 791 of 2000. Loss per movie: 0.7495810229344544, test rmse: 0.89495, train rmse: 0.81300
Epoch 792 of 2000. Loss per movie: 0.7495185309017739, test rmse: 0.89494, train rmse: 0.81297
Epoch 793 of 2000. Loss per movie: 0.7494562036500675, test rmse: 0.89494, train rmse: 0.81294
Epoch 794 of 2000. Loss per movie: 0.74939395634371

Epoch 871 of 2000. Loss per movie: 0.7449765949555441, test rmse: 0.89471, train rmse: 0.81051
Epoch 872 of 2000. Loss per movie: 0.7449240440704309, test rmse: 0.89471, train rmse: 0.81048
Epoch 873 of 2000. Loss per movie: 0.7448715887228459, test rmse: 0.89471, train rmse: 0.81045
Epoch 874 of 2000. Loss per movie: 0.744819280508724, test rmse: 0.89471, train rmse: 0.81043
Epoch 875 of 2000. Loss per movie: 0.7447670739272545, test rmse: 0.89470, train rmse: 0.81040
Epoch 876 of 2000. Loss per movie: 0.7447149786881119, test rmse: 0.89470, train rmse: 0.81037
Epoch 877 of 2000. Loss per movie: 0.7446630188174254, test rmse: 0.89470, train rmse: 0.81034
Epoch 878 of 2000. Loss per movie: 0.7446111792191313, test rmse: 0.89470, train rmse: 0.81031
Epoch 879 of 2000. Loss per movie: 0.7445594350166185, test rmse: 0.89469, train rmse: 0.81029
Epoch 880 of 2000. Loss per movie: 0.7445078083224302, test rmse: 0.89469, train rmse: 0.81026
Epoch 881 of 2000. Loss per movie: 0.74445630126277

Epoch 958 of 2000. Loss per movie: 0.7407812654759456, test rmse: 0.89456, train rmse: 0.80824
Epoch 959 of 2000. Loss per movie: 0.7407370622177896, test rmse: 0.89456, train rmse: 0.80821
Epoch 960 of 2000. Loss per movie: 0.7406929831300706, test rmse: 0.89456, train rmse: 0.80819
Epoch 961 of 2000. Loss per movie: 0.7406489721518209, test rmse: 0.89456, train rmse: 0.80816
Epoch 962 of 2000. Loss per movie: 0.7406050467888041, test rmse: 0.89456, train rmse: 0.80814
Epoch 963 of 2000. Loss per movie: 0.7405612290118169, test rmse: 0.89456, train rmse: 0.80812
Epoch 964 of 2000. Loss per movie: 0.7405175051422663, test rmse: 0.89456, train rmse: 0.80809
Epoch 965 of 2000. Loss per movie: 0.7404738550520681, test rmse: 0.89455, train rmse: 0.80807
Epoch 966 of 2000. Loss per movie: 0.7404303183595292, test rmse: 0.89455, train rmse: 0.80804
Epoch 967 of 2000. Loss per movie: 0.7403868348221433, test rmse: 0.89455, train rmse: 0.80802
Epoch 968 of 2000. Loss per movie: 0.7403434496572

Epoch 1044 of 2000. Loss per movie: 0.7372475958891063, test rmse: 0.89449, train rmse: 0.80631
Epoch 1045 of 2000. Loss per movie: 0.7372084856033325, test rmse: 0.89449, train rmse: 0.80629
Epoch 1046 of 2000. Loss per movie: 0.7371694703589722, test rmse: 0.89449, train rmse: 0.80627
Epoch 1047 of 2000. Loss per movie: 0.7371305167037157, test rmse: 0.89449, train rmse: 0.80625
Epoch 1048 of 2000. Loss per movie: 0.7370916499394157, test rmse: 0.89449, train rmse: 0.80623
Epoch 1049 of 2000. Loss per movie: 0.7370528583010652, test rmse: 0.89449, train rmse: 0.80621
Epoch 1050 of 2000. Loss per movie: 0.7370141724769057, test rmse: 0.89449, train rmse: 0.80619
Epoch 1051 of 2000. Loss per movie: 0.7369756002630263, test rmse: 0.89449, train rmse: 0.80616
Epoch 1052 of 2000. Loss per movie: 0.7369370820547823, test rmse: 0.89449, train rmse: 0.80614
Epoch 1053 of 2000. Loss per movie: 0.7368986761102212, test rmse: 0.89449, train rmse: 0.80612
Epoch 1054 of 2000. Loss per movie: 0.73

Epoch 1130 of 2000. Loss per movie: 0.7341135828163338, test rmse: 0.89441, train rmse: 0.80460
Epoch 1131 of 2000. Loss per movie: 0.7340790655610111, test rmse: 0.89441, train rmse: 0.80458
Epoch 1132 of 2000. Loss per movie: 0.734044569496876, test rmse: 0.89441, train rmse: 0.80457
Epoch 1133 of 2000. Loss per movie: 0.7340100878909425, test rmse: 0.89440, train rmse: 0.80455
Epoch 1134 of 2000. Loss per movie: 0.7339756051510324, test rmse: 0.89440, train rmse: 0.80453
Epoch 1135 of 2000. Loss per movie: 0.7339411759915164, test rmse: 0.89440, train rmse: 0.80451
Epoch 1136 of 2000. Loss per movie: 0.7339067409494969, test rmse: 0.89440, train rmse: 0.80449
Epoch 1137 of 2000. Loss per movie: 0.7338723514791617, test rmse: 0.89440, train rmse: 0.80447
Epoch 1138 of 2000. Loss per movie: 0.7338379724272366, test rmse: 0.89440, train rmse: 0.80445
Epoch 1139 of 2000. Loss per movie: 0.7338036056364334, test rmse: 0.89439, train rmse: 0.80443
Epoch 1140 of 2000. Loss per movie: 0.733

Epoch 1216 of 2000. Loss per movie: 0.7312523080534373, test rmse: 0.89426, train rmse: 0.80304
Epoch 1217 of 2000. Loss per movie: 0.7312202041129294, test rmse: 0.89426, train rmse: 0.80302
Epoch 1218 of 2000. Loss per movie: 0.7311881107325786, test rmse: 0.89425, train rmse: 0.80300
Epoch 1219 of 2000. Loss per movie: 0.7311560443550454, test rmse: 0.89425, train rmse: 0.80299
Epoch 1220 of 2000. Loss per movie: 0.731124020147267, test rmse: 0.89425, train rmse: 0.80297
Epoch 1221 of 2000. Loss per movie: 0.7310920087675986, test rmse: 0.89425, train rmse: 0.80295
Epoch 1222 of 2000. Loss per movie: 0.7310600336043078, test rmse: 0.89425, train rmse: 0.80293
Epoch 1223 of 2000. Loss per movie: 0.7310280838846168, test rmse: 0.89425, train rmse: 0.80292
Epoch 1224 of 2000. Loss per movie: 0.7309961785317601, test rmse: 0.89424, train rmse: 0.80290
Epoch 1225 of 2000. Loss per movie: 0.7309642860778872, test rmse: 0.89424, train rmse: 0.80288
Epoch 1226 of 2000. Loss per movie: 0.730

Epoch 1302 of 2000. Loss per movie: 0.7286066556799, test rmse: 0.89413, train rmse: 0.80159
Epoch 1303 of 2000. Loss per movie: 0.7285773482674226, test rmse: 0.89413, train rmse: 0.80157
Epoch 1304 of 2000. Loss per movie: 0.7285481305099696, test rmse: 0.89413, train rmse: 0.80156
Epoch 1305 of 2000. Loss per movie: 0.7285189099175752, test rmse: 0.89412, train rmse: 0.80154
Epoch 1306 of 2000. Loss per movie: 0.7284897305027058, test rmse: 0.89412, train rmse: 0.80153
Epoch 1307 of 2000. Loss per movie: 0.7284605651916704, test rmse: 0.89412, train rmse: 0.80151
Epoch 1308 of 2000. Loss per movie: 0.728431428797038, test rmse: 0.89412, train rmse: 0.80149
Epoch 1309 of 2000. Loss per movie: 0.7284023299653805, test rmse: 0.89412, train rmse: 0.80148
Epoch 1310 of 2000. Loss per movie: 0.7283732876199321, test rmse: 0.89412, train rmse: 0.80146
Epoch 1311 of 2000. Loss per movie: 0.7283442569686173, test rmse: 0.89412, train rmse: 0.80145
Epoch 1312 of 2000. Loss per movie: 0.728315

Epoch 1388 of 2000. Loss per movie: 0.7262136838382263, test rmse: 0.89404, train rmse: 0.80028
Epoch 1389 of 2000. Loss per movie: 0.7261875817523417, test rmse: 0.89404, train rmse: 0.80026
Epoch 1390 of 2000. Loss per movie: 0.7261615754874793, test rmse: 0.89403, train rmse: 0.80025
Epoch 1391 of 2000. Loss per movie: 0.7261355388178695, test rmse: 0.89403, train rmse: 0.80023
Epoch 1392 of 2000. Loss per movie: 0.7261095811013801, test rmse: 0.89403, train rmse: 0.80022
Epoch 1393 of 2000. Loss per movie: 0.7260836351498979, test rmse: 0.89403, train rmse: 0.80021
Epoch 1394 of 2000. Loss per movie: 0.726057755465173, test rmse: 0.89403, train rmse: 0.80019
Epoch 1395 of 2000. Loss per movie: 0.726031902428898, test rmse: 0.89403, train rmse: 0.80018
Epoch 1396 of 2000. Loss per movie: 0.7260060661187778, test rmse: 0.89403, train rmse: 0.80016
Epoch 1397 of 2000. Loss per movie: 0.7259802806958574, test rmse: 0.89403, train rmse: 0.80015
Epoch 1398 of 2000. Loss per movie: 0.7259

Epoch 1474 of 2000. Loss per movie: 0.7240668616737111, test rmse: 0.89393, train rmse: 0.79910
Epoch 1475 of 2000. Loss per movie: 0.7240428724697172, test rmse: 0.89393, train rmse: 0.79908
Epoch 1476 of 2000. Loss per movie: 0.7240189106937821, test rmse: 0.89392, train rmse: 0.79907
Epoch 1477 of 2000. Loss per movie: 0.7239949911584752, test rmse: 0.89392, train rmse: 0.79906
Epoch 1478 of 2000. Loss per movie: 0.7239710916803793, test rmse: 0.89392, train rmse: 0.79904
Epoch 1479 of 2000. Loss per movie: 0.7239472309701083, test rmse: 0.89392, train rmse: 0.79903
Epoch 1480 of 2000. Loss per movie: 0.7239234304314703, test rmse: 0.89392, train rmse: 0.79902
Epoch 1481 of 2000. Loss per movie: 0.7238996339326239, test rmse: 0.89392, train rmse: 0.79900
Epoch 1482 of 2000. Loss per movie: 0.7238758749967523, test rmse: 0.89392, train rmse: 0.79899
Epoch 1483 of 2000. Loss per movie: 0.7238521693577806, test rmse: 0.89392, train rmse: 0.79898
Epoch 1484 of 2000. Loss per movie: 0.72

Epoch 1560 of 2000. Loss per movie: 0.7221279924604754, test rmse: 0.89389, train rmse: 0.79803
Epoch 1561 of 2000. Loss per movie: 0.7221067581817454, test rmse: 0.89389, train rmse: 0.79802
Epoch 1562 of 2000. Loss per movie: 0.7220855840037751, test rmse: 0.89389, train rmse: 0.79801
Epoch 1563 of 2000. Loss per movie: 0.7220644461839293, test rmse: 0.89389, train rmse: 0.79800
Epoch 1564 of 2000. Loss per movie: 0.7220433174358962, test rmse: 0.89389, train rmse: 0.79798
Epoch 1565 of 2000. Loss per movie: 0.722022219943093, test rmse: 0.89389, train rmse: 0.79797
Epoch 1566 of 2000. Loss per movie: 0.7220011676676067, test rmse: 0.89389, train rmse: 0.79796
Epoch 1567 of 2000. Loss per movie: 0.7219801199280266, test rmse: 0.89389, train rmse: 0.79795
Epoch 1568 of 2000. Loss per movie: 0.7219591052155149, test rmse: 0.89389, train rmse: 0.79794
Epoch 1569 of 2000. Loss per movie: 0.7219381422406853, test rmse: 0.89389, train rmse: 0.79793
Epoch 1570 of 2000. Loss per movie: 0.721

Epoch 1646 of 2000. Loss per movie: 0.7203982279643718, test rmse: 0.89390, train rmse: 0.79708
Epoch 1647 of 2000. Loss per movie: 0.7203790368279719, test rmse: 0.89390, train rmse: 0.79707
Epoch 1648 of 2000. Loss per movie: 0.7203598867982236, test rmse: 0.89390, train rmse: 0.79706
Epoch 1649 of 2000. Loss per movie: 0.7203407625664429, test rmse: 0.89390, train rmse: 0.79705
Epoch 1650 of 2000. Loss per movie: 0.7203216482569573, test rmse: 0.89390, train rmse: 0.79703
Epoch 1651 of 2000. Loss per movie: 0.7203025377037693, test rmse: 0.89390, train rmse: 0.79702
Epoch 1652 of 2000. Loss per movie: 0.7202834688950945, test rmse: 0.89390, train rmse: 0.79701
Epoch 1653 of 2000. Loss per movie: 0.7202643940621692, test rmse: 0.89390, train rmse: 0.79700
Epoch 1654 of 2000. Loss per movie: 0.720245352752427, test rmse: 0.89390, train rmse: 0.79699
Epoch 1655 of 2000. Loss per movie: 0.7202262962048742, test rmse: 0.89390, train rmse: 0.79698
Epoch 1656 of 2000. Loss per movie: 0.720

Epoch 1732 of 2000. Loss per movie: 0.7188083696025164, test rmse: 0.89391, train rmse: 0.79620
Epoch 1733 of 2000. Loss per movie: 0.7187905831796235, test rmse: 0.89391, train rmse: 0.79619
Epoch 1734 of 2000. Loss per movie: 0.7187727817315409, test rmse: 0.89391, train rmse: 0.79618
Epoch 1735 of 2000. Loss per movie: 0.7187550121765499, test rmse: 0.89391, train rmse: 0.79617
Epoch 1736 of 2000. Loss per movie: 0.7187372329118844, test rmse: 0.89391, train rmse: 0.79616
Epoch 1737 of 2000. Loss per movie: 0.7187194951791117, test rmse: 0.89391, train rmse: 0.79615
Epoch 1738 of 2000. Loss per movie: 0.7187017654550487, test rmse: 0.89391, train rmse: 0.79614
Epoch 1739 of 2000. Loss per movie: 0.7186840481338547, test rmse: 0.89391, train rmse: 0.79613
Epoch 1740 of 2000. Loss per movie: 0.7186663478931831, test rmse: 0.89391, train rmse: 0.79612
Epoch 1741 of 2000. Loss per movie: 0.7186486658670106, test rmse: 0.89391, train rmse: 0.79611
Epoch 1742 of 2000. Loss per movie: 0.71

Epoch 1818 of 2000. Loss per movie: 0.7173448068208275, test rmse: 0.89393, train rmse: 0.79539
Epoch 1819 of 2000. Loss per movie: 0.7173286768542458, test rmse: 0.89393, train rmse: 0.79538
Epoch 1820 of 2000. Loss per movie: 0.7173125899079014, test rmse: 0.89393, train rmse: 0.79537
Epoch 1821 of 2000. Loss per movie: 0.7172965195459645, test rmse: 0.89393, train rmse: 0.79536
Epoch 1822 of 2000. Loss per movie: 0.717280490786794, test rmse: 0.89393, train rmse: 0.79536
Epoch 1823 of 2000. Loss per movie: 0.7172644580587054, test rmse: 0.89393, train rmse: 0.79535
Epoch 1824 of 2000. Loss per movie: 0.7172484712566689, test rmse: 0.89393, train rmse: 0.79534
Epoch 1825 of 2000. Loss per movie: 0.7172324965740072, test rmse: 0.89393, train rmse: 0.79533
Epoch 1826 of 2000. Loss per movie: 0.7172165221748398, test rmse: 0.89393, train rmse: 0.79532
Epoch 1827 of 2000. Loss per movie: 0.7172005849842793, test rmse: 0.89393, train rmse: 0.79531
Epoch 1828 of 2000. Loss per movie: 0.717

Epoch 1904 of 2000. Loss per movie: 0.7160260869404932, test rmse: 0.89393, train rmse: 0.79466
Epoch 1905 of 2000. Loss per movie: 0.7160114202998339, test rmse: 0.89393, train rmse: 0.79465
Epoch 1906 of 2000. Loss per movie: 0.7159967292078043, test rmse: 0.89393, train rmse: 0.79465
Epoch 1907 of 2000. Loss per movie: 0.71598211295823, test rmse: 0.89393, train rmse: 0.79464
Epoch 1908 of 2000. Loss per movie: 0.7159674485855239, test rmse: 0.89393, train rmse: 0.79463
Epoch 1909 of 2000. Loss per movie: 0.7159528136253357, test rmse: 0.89393, train rmse: 0.79462
Epoch 1910 of 2000. Loss per movie: 0.7159382149523985, test rmse: 0.89393, train rmse: 0.79461
Epoch 1911 of 2000. Loss per movie: 0.7159235953008944, test rmse: 0.89393, train rmse: 0.79461
Epoch 1912 of 2000. Loss per movie: 0.7159090159055594, test rmse: 0.89393, train rmse: 0.79460
Epoch 1913 of 2000. Loss per movie: 0.715894426162688, test rmse: 0.89393, train rmse: 0.79459
Epoch 1914 of 2000. Loss per movie: 0.71587

Epoch 1990 of 2000. Loss per movie: 0.7148036822836125, test rmse: 0.89393, train rmse: 0.79399
Epoch 1991 of 2000. Loss per movie: 0.7147899710182344, test rmse: 0.89393, train rmse: 0.79398
Epoch 1992 of 2000. Loss per movie: 0.7147762709508753, test rmse: 0.89393, train rmse: 0.79397
Epoch 1993 of 2000. Loss per movie: 0.7147625818689144, test rmse: 0.89393, train rmse: 0.79396
Epoch 1994 of 2000. Loss per movie: 0.7147489119936822, test rmse: 0.89393, train rmse: 0.79396
Epoch 1995 of 2000. Loss per movie: 0.7147352651523495, test rmse: 0.89393, train rmse: 0.79395
Epoch 1996 of 2000. Loss per movie: 0.7147216149799606, test rmse: 0.89393, train rmse: 0.79394
Epoch 1997 of 2000. Loss per movie: 0.7147079944327102, test rmse: 0.89393, train rmse: 0.79393
Epoch 1998 of 2000. Loss per movie: 0.7146943911077293, test rmse: 0.89393, train rmse: 0.79392
Epoch 1999 of 2000. Loss per movie: 0.7146807766556031, test rmse: 0.89393, train rmse: 0.79392


In [92]:
x = tf.constant([[3.0, 4.0], [3.0, 4.0]])
tf.math.l2_normalize(x, axis=1).numpy()

array([[0.6, 0.8],
       [0.6, 0.8]], dtype=float32)

In [119]:
x * 10.0

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[30., 40.],
       [30., 40.]], dtype=float32)>

In [136]:
import pandas as pd
folder = 'C:/Users/Ahmad/Documents/Jupyter notebooks/movielens/ml-100k'
items_cols = "movie id | movie title | release date | video release date | IMDb URL | unknown | Action | Adventure | Animation | Children's | Comedy | Crime | Documentary | Drama | Fantasy | Film-Noir | Horror | Musical | Mystery | Romance | Sci-Fi | Thriller | War | Western"
items_cols = items_cols.split(' | ')
data1 = pd.read_csv(folder + '/u.item', sep='|', encoding='iso-8859-1', names=items_cols)

In [138]:
data1.columns

Index(['movie id', 'movie title', 'release date', 'video release date',
       'IMDb URL', 'unknown', 'Action', 'Adventure', 'Animation', 'Children's',
       'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir',
       'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War',
       'Western'],
      dtype='object')

In [139]:
data_cols = "user id | item id | rating | timestamp".split(' | ')
data = pd.read_csv(folder + '/u.data', sep='\t', encoding='iso-8859-1', names=data_cols)

In [140]:
data2 = pd.read_csv(folder + '/u1.base', sep='\t', encoding='iso-8859-1', names=data_cols)

In [141]:
data2

user id  item id  rating  timestamp
0            1        1       5  874965758
1            1        2       3  876893171
2            1        3       4  878542960
3            1        4       3  876893119
4            1        5       3  889751712
...        ...      ...     ...        ...
79995      943     1067       2  875501756
79996      943     1074       4  888640250
79997      943     1188       3  888640250
79998      943     1228       3  888640275
79999      943     1330       3  888692465

[80000 rows x 4 columns]

In [142]:
data

user id  item id  rating  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

In [148]:
ratings = np.array(
    [[0.1, 0.9, 1.0],
     [0.3, 0.8, 0.8],
     [0.8, 0.1, 0.2]], dtype='float32')

In [149]:
tf.constant(ratings) @ tf.constant(ratings)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.08      , 0.90999997, 1.02      ],
       [0.9100001 , 0.99000007, 1.1       ],
       [0.27      , 0.81999993, 0.92      ]], dtype=float32)>

In [150]:
tf.constant(ratings)[0, :] @ tf.constant(ratings)[0, :]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.1, 0.9, 1. ], dtype=float32)>

In [7]:
ml = MovieLens()
mat = ml.mat.transpose().astype('float32') # shape [items, users]
train_mask, test_mask = ml.train_test_split(mask=ml.mat_ind.transpose(), test_size=0.05)
validation_mask, test_mask = ml.train_test_split(mask=test_mask, test_size=0.5)

train_mask = train_mask.astype(np.float32)
validation_mask = validation_mask.astype(np.float32)
test_mask = test_mask.astype(np.float32)

In [228]:
autorec = AutoRec(m=mat.shape[1], k=200)
autorec.create_model()

In [229]:
autorec.fit(mat, train_mask, max_epochs=2000, validation_mask=validation_mask, alpha=0.1, optimizer=keras.optimizers.Adam(lr=1e-4))

Epoch 0 of 2000. Epoch loss: 1901.60796, validation rmse: 1.32634, train rmse: 1.32319
Epoch 1 of 2000. Epoch loss: 1638.07111, validation rmse: 1.26741, train rmse: 1.25850
Epoch 2 of 2000. Epoch loss: 1487.07471, validation rmse: 1.22352, train rmse: 1.20877
Epoch 3 of 2000. Epoch loss: 1374.55220, validation rmse: 1.18752, train rmse: 1.16719
Epoch 4 of 2000. Epoch loss: 1283.02793, validation rmse: 1.15650, train rmse: 1.13057
Epoch 5 of 2000. Epoch loss: 1204.96891, validation rmse: 1.12990, train rmse: 1.09871
Epoch 6 of 2000. Epoch loss: 1139.49163, validation rmse: 1.10821, train rmse: 1.07224
Epoch 7 of 2000. Epoch loss: 1086.79321, validation rmse: 1.09048, train rmse: 1.05082
Epoch 8 of 2000. Epoch loss: 1045.06169, validation rmse: 1.07685, train rmse: 1.03343
Epoch 9 of 2000. Epoch loss: 1011.71471, validation rmse: 1.06557, train rmse: 1.01917
Epoch 10 of 2000. Epoch loss: 984.66938, validation rmse: 1.05609, train rmse: 1.00707
Epoch 11 of 2000. Epoch loss: 961.89120, va

Epoch 95 of 2000. Epoch loss: 566.98252, validation rmse: 0.91483, train rmse: 0.77268
Epoch 96 of 2000. Epoch loss: 566.26863, validation rmse: 0.90143, train rmse: 0.77401
Epoch 97 of 2000. Epoch loss: 567.80377, validation rmse: 0.91832, train rmse: 0.77487
Epoch 98 of 2000. Epoch loss: 567.92818, validation rmse: 0.90256, train rmse: 0.77781
Epoch 99 of 2000. Epoch loss: 571.16591, validation rmse: 0.92233, train rmse: 0.77822
Epoch 100 of 2000. Epoch loss: 570.91866, validation rmse: 0.90414, train rmse: 0.78108
Epoch 101 of 2000. Epoch loss: 574.47186, validation rmse: 0.92119, train rmse: 0.77749
Epoch 102 of 2000. Epoch loss: 570.39726, validation rmse: 0.90250, train rmse: 0.77745
Epoch 103 of 2000. Epoch loss: 570.63393, validation rmse: 0.91539, train rmse: 0.77261
Epoch 104 of 2000. Epoch loss: 565.61670, validation rmse: 0.90003, train rmse: 0.77126
Epoch 105 of 2000. Epoch loss: 563.82456, validation rmse: 0.91037, train rmse: 0.76850
Epoch 106 of 2000. Epoch loss: 561.19

In [183]:
Best validation rmse: 0.88956, k=300, alpha=0.2

943

In [ ]:
Best validation rmse: 0.88296, k=100, alpha=0.2

In [18]:
# Do a grid search
res = []
for alpha in [0.01, 0.1, 1.0]:
    for activation1 in ['relu', 'sigmoid']:
        for activation2 in ['relu', 'sigmoid']:
            for k in [50, 100, 200, 300]:
                autorec = AutoRec(m=mat.shape[1], k=k)
                autorec.create_model()
                best_model, rmse = autorec.fit(mat, train_mask, max_epochs=1000, validation_mask=validation_mask, verbose=False,
                                   alpha=alpha, optimizer=keras.optimizers.Adam(lr=1e-4))
                res.append({'alpha':alpha, 'activation1':activation1, 'activation2':activation2, 
                            'k':k, 'rmse':rmse, 'model':best_model})
                print(res[-1])

{'alpha': 0.01, 'activation1': 'relu', 'activation2': 'relu', 'k': 50, 'rmse': 0.89449304, 'model': <autorec.AutoRec object at 0x0000016136B58CF8>}
{'alpha': 0.01, 'activation1': 'relu', 'activation2': 'relu', 'k': 100, 'rmse': 0.8970445, 'model': <autorec.AutoRec object at 0x0000015FB16360F0>}
{'alpha': 0.01, 'activation1': 'relu', 'activation2': 'relu', 'k': 200, 'rmse': 0.9014169, 'model': <autorec.AutoRec object at 0x00000161247BF320>}
{'alpha': 0.01, 'activation1': 'relu', 'activation2': 'relu', 'k': 300, 'rmse': 0.8944723, 'model': <autorec.AutoRec object at 0x0000016136B9BBA8>}
{'alpha': 0.01, 'activation1': 'relu', 'activation2': 'sigmoid', 'k': 50, 'rmse': 0.8961052, 'model': <autorec.AutoRec object at 0x000001613D03F898>}
{'alpha': 0.01, 'activation1': 'relu', 'activation2': 'sigmoid', 'k': 100, 'rmse': 0.89458317, 'model': <autorec.AutoRec object at 0x0000015FB2D13208>}
{'alpha': 0.01, 'activation1': 'relu', 'activation2': 'sigmoid', 'k': 200, 'rmse': 0.8970079, 'model': <au

In [14]:
autorec = AutoRec(m=mat.shape[1], k=200, activation1='relu', activation2='relu')
autorec.create_model()

In [15]:
autorec.fit(mat, train_mask, max_epochs=1000, validation_mask=validation_mask, alpha=0.01, optimizer=keras.optimizers.Adam(lr=1e-4))

Epoch 0 of 1000. Epoch loss: 6458.14147, validation rmse: 2.38761, train rmse: 2.38336
Epoch 1 of 1000. Epoch loss: 5335.63937, validation rmse: 2.30039, train rmse: 2.28501
Epoch 2 of 1000. Epoch loss: 4908.13789, validation rmse: 2.22918, train rmse: 2.20539
Epoch 3 of 1000. Epoch loss: 4571.35740, validation rmse: 2.16504, train rmse: 2.13073
Epoch 4 of 1000. Epoch loss: 4266.07818, validation rmse: 2.10636, train rmse: 2.05849
Epoch 5 of 1000. Epoch loss: 3982.58365, validation rmse: 2.05228, train rmse: 1.98917
Epoch 6 of 1000. Epoch loss: 3720.32765, validation rmse: 2.00450, train rmse: 1.92300
Epoch 7 of 1000. Epoch loss: 3477.39129, validation rmse: 1.96013, train rmse: 1.85885
Epoch 8 of 1000. Epoch loss: 3250.46512, validation rmse: 1.91966, train rmse: 1.79805
Epoch 9 of 1000. Epoch loss: 3042.80303, validation rmse: 1.88273, train rmse: 1.74074
Epoch 10 of 1000. Epoch loss: 2853.23395, validation rmse: 1.84597, train rmse: 1.68592
Epoch 11 of 1000. Epoch loss: 2677.66982, 

Epoch 94 of 1000. Epoch loss: 421.38791, validation rmse: 1.20139, train rmse: 0.67666
Epoch 95 of 1000. Epoch loss: 422.23791, validation rmse: 1.20148, train rmse: 0.67307
Epoch 96 of 1000. Epoch loss: 418.88398, validation rmse: 1.20375, train rmse: 0.68314
Epoch 97 of 1000. Epoch loss: 424.63996, validation rmse: 1.20408, train rmse: 0.68133
Epoch 98 of 1000. Epoch loss: 422.12479, validation rmse: 1.21198, train rmse: 0.69866
Epoch 99 of 1000. Epoch loss: 435.27308, validation rmse: 1.21272, train rmse: 0.69921
Epoch 100 of 1000. Epoch loss: 432.96986, validation rmse: 1.22507, train rmse: 0.72664
Epoch 101 of 1000. Epoch loss: 458.70447, validation rmse: 1.22264, train rmse: 0.72474
Epoch 102 of 1000. Epoch loss: 451.00646, validation rmse: 1.24424, train rmse: 0.75949
Epoch 103 of 1000. Epoch loss: 489.33161, validation rmse: 1.23520, train rmse: 0.74759
Epoch 104 of 1000. Epoch loss: 467.92354, validation rmse: 1.25460, train rmse: 0.78124
Epoch 105 of 1000. Epoch loss: 512.494

Epoch 188 of 1000. Epoch loss: 278.14819, validation rmse: 1.19150, train rmse: 0.60593
Epoch 189 of 1000. Epoch loss: 302.31293, validation rmse: 1.11994, train rmse: 0.56843
Epoch 190 of 1000. Epoch loss: 268.62602, validation rmse: 1.18043, train rmse: 0.58307
Epoch 191 of 1000. Epoch loss: 284.31679, validation rmse: 1.11515, train rmse: 0.54760
Epoch 192 of 1000. Epoch loss: 255.65011, validation rmse: 1.17109, train rmse: 0.55769
Epoch 193 of 1000. Epoch loss: 264.78754, validation rmse: 1.11140, train rmse: 0.52842
Epoch 194 of 1000. Epoch loss: 243.08620, validation rmse: 1.16230, train rmse: 0.53747
Epoch 195 of 1000. Epoch loss: 249.58202, validation rmse: 1.10809, train rmse: 0.51540
Epoch 196 of 1000. Epoch loss: 234.26476, validation rmse: 1.15737, train rmse: 0.52556
Epoch 197 of 1000. Epoch loss: 240.65169, validation rmse: 1.10654, train rmse: 0.50744
Epoch 198 of 1000. Epoch loss: 228.33316, validation rmse: 1.15464, train rmse: 0.51844
Epoch 199 of 1000. Epoch loss: 2

Epoch 282 of 1000. Epoch loss: 199.60607, validation rmse: 1.16407, train rmse: 0.51292
Epoch 283 of 1000. Epoch loss: 217.08671, validation rmse: 1.07646, train rmse: 0.49436
Epoch 284 of 1000. Epoch loss: 200.36017, validation rmse: 1.16336, train rmse: 0.51422
Epoch 285 of 1000. Epoch loss: 217.74164, validation rmse: 1.07682, train rmse: 0.49633
Epoch 286 of 1000. Epoch loss: 201.32320, validation rmse: 1.16561, train rmse: 0.51932
Epoch 287 of 1000. Epoch loss: 221.17978, validation rmse: 1.07810, train rmse: 0.49846
Epoch 288 of 1000. Epoch loss: 202.40297, validation rmse: 1.16557, train rmse: 0.51994
Epoch 289 of 1000. Epoch loss: 221.66961, validation rmse: 1.07743, train rmse: 0.49639
Epoch 290 of 1000. Epoch loss: 201.44079, validation rmse: 1.16675, train rmse: 0.51770
Epoch 291 of 1000. Epoch loss: 219.90585, validation rmse: 1.07626, train rmse: 0.49388
Epoch 292 of 1000. Epoch loss: 199.99843, validation rmse: 1.16534, train rmse: 0.51321
Epoch 293 of 1000. Epoch loss: 2

Epoch 376 of 1000. Epoch loss: 174.64230, validation rmse: 1.16118, train rmse: 0.47959
Epoch 377 of 1000. Epoch loss: 189.06993, validation rmse: 1.06610, train rmse: 0.46212
Epoch 378 of 1000. Epoch loss: 174.22533, validation rmse: 1.15889, train rmse: 0.48210
Epoch 379 of 1000. Epoch loss: 190.76349, validation rmse: 1.06521, train rmse: 0.46438
Epoch 380 of 1000. Epoch loss: 174.98141, validation rmse: 1.16062, train rmse: 0.48484
Epoch 381 of 1000. Epoch loss: 192.09138, validation rmse: 1.06737, train rmse: 0.46892
Epoch 382 of 1000. Epoch loss: 176.75259, validation rmse: 1.16130, train rmse: 0.49059
Epoch 383 of 1000. Epoch loss: 195.84484, validation rmse: 1.06417, train rmse: 0.47075
Epoch 384 of 1000. Epoch loss: 177.92939, validation rmse: 1.16477, train rmse: 0.48965
Epoch 385 of 1000. Epoch loss: 195.09873, validation rmse: 1.06428, train rmse: 0.46942
Epoch 386 of 1000. Epoch loss: 177.70438, validation rmse: 1.16393, train rmse: 0.48793
Epoch 387 of 1000. Epoch loss: 1

1.0609013

In [20]:
best_dic, best_rmse = None, np.inf
for i, dic in enumerate(res):
    if dic['rmse'] < best_rmse:
        best_rmse = dic['rmse']
        best_dic = dic

In [21]:
best_rmse

0.8917625

In [22]:
best_dic

{'alpha': 0.01,
 'activation1': 'sigmoid',
 'activation2': 'sigmoid',
 'k': 50,
 'rmse': 0.8917625,
 'model': <autorec.AutoRec at 0x1614448d908>}

In [23]:
best_model = best_dic['model']

In [24]:
best_model.rmse(mat, train_mask, test_mask)

0.89576286